const formatTitle = title => {
  if (title === 'PA') return 'PA(mmHg)'
  if (title === 'FC') return 'FC(bpm)'
  if (title === 'altura') return 'Altura(m)'
  if (title === 'peso') return 'Peso(kg)'
  if (title === 'imc') return 'IMC(kg/m²)'
  if (title === 'bf') return '%Gordura'
  if (title === 'muscular') return '%Muscular'
  if (title === 'taxaMetabolica') return 'Taxa Metabólica(kcal)'
  if (title === 'idadeBio') return 'Idade Biológica(anos)'
  if (title === 'gorduraVisceral') return 'Gordura Visceral'
  if (title === 'cintura') return 'Cintura(cm)'
  if (title === 'quadril') return 'Quadril(cm)'
  if (title === 'bracoRelax') return 'Braço Relaxado(cm)'
  if (title === 'bracoTenso') return 'Braço Tenso(cm)'
  if (title === 'flex') return 'Flexibilidade(cm)'
  if (title === 'agachamento') return 'Agachamento(seg)'
  if (title === 'abdomen') return 'Abdomen 1 min(reps)'
  if (title === 'apoio') return 'Apoio(reps)'
  if (title === 'vo2') return 'VO₂ Max(ml/kg/m)'
  if (title === 'pesoMeta') return 'Peso Meta'
  if (title === 'imcMeta') return 'IMC Meta'
  if (title === 'pccqMeta') return 'PCCQ Meta'
  if (title === 'bfMeta') return '%Gordura Meta'
  if (title === 'muscularMeta') return '%Muscular Meta'
  if (title === 'itmMeta') return 'ITM Meta'
  if (title === 'flexMeta') return 'Flexibilidade Meta'
  if (title === 'agachamentoMeta') return 'Agachamento Meta'
  if (title === 'abdomenMeta') return 'Abodmen Meta'
  if (title === 'apoioMeta') return 'Apoio Meta'
  if (title === 'vo2Meta') return 'VO₂ Meta'
}

export default formatTitle